#!/bin/bash

## Use 'fin develop' instead
##
## init is here for compliance

# Start containers
fin project start

echo "Preparing to install dependencies..."
cd "$PROJECT_ROOT/$DOCROOT"
fin exec npm install

fin develop
