#!/bin/bash

## Initialize project stack
##
## Initializes stack and starts a local development server

# Start containers
echo "Resetting stack..."
fin project reset -f

# Install nodejs dependencies
fin install

# Start development server
fin develop
