#!/usr/bin/env bash

## Build and publish production ready static files to Surge.sh
##
## --no-browser     Will prevent opening browser when ready

SURGE_DOMAIN="docksal-test.surge.sh"

# Rebuild
echo "Rebuilding static files..."
cd "$PROJECT_ROOT/$DOCROOT"
fin exec gatsby build
[[ $? != 0 ]] && exit 1

# Publish to Surge
cd "$PROJECT_ROOT/$DOCROOT/public"
surge "$(pwd)" "$SURGE_DOMAIN"

# Open in browser
[[ $? == 0 ]] && [[ "$1" != "--no-browser" ]] &&
    open "http://$SURGE_DOMAIN"
